const ptBr = {
  lead: {
    address: 'rua',
    addressComplement: 'complemento',
    addressNumber: 'número',
    addressTitle: 'endereço',
    birthDate: 'data de nascimento',
    city: 'cidade',
    CNPJ: 'CNPJ',
    country: 'país',
    course: 'curso',
    courses: 'cursos',
    CPF: 'CPF',
    driversLicense: 'CNH',
    driversLicenseCategory: 'categoria',
    driversLicenseExpiryDate: 'data de expiração',
    driversLicenseNumber: 'número',
    email: 'email',
    fullName: 'nome completo',
    id: 'ID',
    identification: 'identificação',
    identificationNumber: 'número de identificação',
    identificationType: 'tipo do documento de identificação',
    image: 'imagem',
    name: 'nome',
    neighbourhood: 'bairro',
    phoneNumber: 'número de telefone',
    registrationInfo: 'informações de registro',
    sellingPage: 'página de venda',
    state: 'estado',
    subtotal: 'total',
    timestamp: 'data',
    type: 'tipo',
    value: 'valor',
    zipCode: 'código postal',
  }
};

export default ptBr;