const ptBr = {
  leftSidebar: {
    profile: 'perfil',
    leads: 'leads',
    coupons: 'cupom',
    courses: 'cursos'
  },
  lead: {
    address: 'rua',
    addressComplement: 'complemento',
    addressNumber: 'número',
    addressTitle: 'endereço',
    birthDate: 'data de nascimento',
    city: 'cidade',
    CNPJ: 'CNPJ',
    country: 'país',
    course: 'curso',
    courses: 'cursos',
    CPF: 'CPF',
    driversLicense: 'CNH',
    driversLicenseCategory: 'categoria',
    driversLicenseExpiryDate: 'data de expiração',
    firstDriversLicenseIssueDate: 'data da primeira habilitação',
    driversLicenseNumber: 'número',
    email: 'email',
    fullName: 'nome completo',
    id: 'ID',
    identification: 'identificação',
    identificationNumber: 'número de identificação',
    identificationType: 'tipo do documento de identificação',
    image: 'imagem',
    name: 'nome',
    neighbourhood: 'bairro',
    phoneNumber: 'número de telefone',
    registrationInfo: 'informações de registro',
    renachCode: 'RENACH',
    sellingPage: 'página de venda',
    state: 'estado',
    subtotal: 'total',
    timestamp: 'data',
    type: 'tipo',
    value: 'valor',
    zipCode: 'código postal',
    collapseUncollapse: 'minimizar/maximizar',
    edit: 'editar',
    delete: 'deletar',
    amountOfRegisters: 'total de registros encontrados',
    drawerStatus: '{var} o registro',
    visualizing: 'visualizando',
    editing: 'editando',
    confirm: 'confirmar',
    successEdition: 'A edição do registro {var} foi feita com sucesso!',
    failureEdition: 'A edição do registro {var} não pode ser concluída',
    cancelEdition: 'A edição do registro {var} foi cancelada'
  },
  countdown: {
    and: 'e',
    days: 'dias',
    finishesIn: 'acaba em',
    hours: 'horas',
    minutes: 'minutos',
    seconds: 'segundos'
  }
};

export default ptBr;