export const SET_AVAILABLE_COURSES = 'SET_AVAILABLE_COURSES';
export const SET_CART = 'SET_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const SET_REGISTRATION_INFO = 'SET_REGISTRATION_INFO';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';